swagger: '3.1.0'
info:
  title: Your API Documentation
  version: 1.0.0
paths:
  /image-gallery/all:
    get:
      tags:
        - Image Gallery
      summary: Retrieve all images from the gallery
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation

  /image-gallery/upload:
    post:
      tags:
        - Image Gallery
      summary: Upload images to the gallery
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '201':
          description: Images uploaded successfully
        '500':
          description: Internal Server Error

  /image-gallery/delete:
    post:
      tags:
        - Image Gallery
      summary: Delete an image from the gallery
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageId:
                  type: string
      responses:
        '204':
          description: Image deleted successfully
        '404':
          description: Image not found
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    bearerAuth:
      type: jwt
      in: header
      name: Authorization
