swagger: '3.1.0'
info:
  title: Inventory System API Documentation
  version: 1.0.0
paths:
  /units/all:
    get:
      summary: Get all units
      responses:
        '200':
          description: A list of units
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unit'
  /units/{id}:
    get:
      summary: Get a unit by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A unit object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
        '404':
          description: Unit not found
    put:
      summary: Update a unit by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unit'
      responses:
        '200':
          description: The updated unit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
        '404':
          description: Unit not found
    delete:
      summary: Delete a unit by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Unit deleted successfully
        '404':
          description: Unit not found
  /units/create:
    post:
      summary: Create a new unit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unit'
      responses:
        '201':
          description: The created unit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unit'
components:
  schemas:
    Unit:
      type: object
      properties:
        id:
          type: string
          example: 60c72b2f5f1b2c001c8e4d62
        unit_code:
          type: string
          example: KG
        name:
          type: string
          example: Kilogram
        base_unit:
          type: string
          example: 60c72b2f5f1b2c001c8e4d63
        operator:
          type: string
          enum: ['*', '/', '+', '-']
          example: '*'
        operation_value:
          type: number
          example: 1
