---
components:
  schemas:
    CreateCustomer:
      properties:
        address:
          maxLength: 255
          minLength: 1
          type: string
        city:
          maxLength: 100
          minLength: 1
          type: string
        email:
          format: email
          type: string
        name:
          maxLength: 255
          minLength: 1
          type: string
        phone:
          pattern: ^(\\+88|0088)?(01[3456789]{1}[0-9]{8})$
          type: string
        postalCode:
          maxLength: 20
          type: string
        state:
          maxLength: 100
          type: string
      required:
        - name
        - email
        - phone
        - address
        - city
      type: object
    UpdateCustomer:
      properties:
        address:
          maxLength: 255
          minLength: 1
          type: string
        city:
          maxLength: 100
          minLength: 1
          type: string
        email:
          format: email
          type: string
        name:
          maxLength: 255
          minLength: 1
          type: string
        phone:
          pattern: ^(\\+88|0088)?(01[3456789]{1}[0-9]{8})?$
          type: string
        postalCode:
          maxLength: 20
          type: string
        state:
          maxLength: 100
          type: string
      type: object
info:
  title: Customer API Documentation
  version: 1.0.0
paths:
  /customers/all:
    get:
      responses:
        '200':
          description: A list of customers
      summary: Retrieve all customers
  /customers/create:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomer'
        required: true
      responses:
        '200':
          description: Successfully created a new customer
      summary: Create a new customer
  /customers/update/{id}:
    delete:
      parameters:
        - description: ID of the customer to delete
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the customer
      summary: Delete a customer by ID
    put:
      parameters:
        - description: ID of the customer to update
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomer'
        required: true
      responses:
        '200':
          description: Successfully updated the customer
      summary: Update an existing customer by ID
  /customers/{id}:
    get:
      parameters:
        - description: ID of the customer to retrieve
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer details
      summary: Retrieve a customer by ID
swagger: 3.1.0
