---
info:
  title: Your API Documentation
  version: 1.0.0
paths:
  /combo:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Combo'
                type: array
          description: OK
      summary: Get all combos
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Combo'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Combo'
          description: Created
      summary: Create a new combo
  /combo/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
      summary: Delete a combo by id
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Combo'
          description: OK
      summary: Get a combo by id
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Combo'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Combo'
          description: OK
      summary: Update a combo by id
swagger: 3.1.0
