---
components:
  schemas:
    CreateBiller:
      properties:
        address:
          maxLength: 255
          minLength: 1
          type: string
        city:
          maxLength: 100
          minLength: 1
          type: string
        company:
          maxLength: 255
          minLength: 1
          type: string
        country:
          maxLength: 100
          minLength: 1
          type: string
        emailAddress:
          format: email
          type: string
        gstNumber:
          maxLength: 50
          type: string
        name:
          maxLength: 255
          minLength: 1
          type: string
        phone:
          pattern: ^(\\+88|0088)?(01[3456789]{1}[0-9]{8})$
          type: string
        postalCode:
          maxLength: 20
          type: string
        state:
          maxLength: 100
          type: string
        vatNumber:
          maxLength: 50
          type: string
      required:
        - company
        - name
        - emailAddress
        - phone
        - address
        - city
        - country
      type: object
    UpdateBiller:
      properties:
        address:
          maxLength: 255
          minLength: 1
          type: string
        city:
          maxLength: 100
          minLength: 1
          type: string
        company:
          maxLength: 255
          minLength: 1
          type: string
        country:
          maxLength: 100
          minLength: 1
          type: string
        emailAddress:
          format: email
          type: string
        gstNumber:
          maxLength: 50
          type: string
        name:
          maxLength: 255
          minLength: 1
          type: string
        phone:
          pattern: ^(\\+88|0088)?(01[3456789]{1}[0-9]{8})?$
          type: string
        postalCode:
          maxLength: 20
          type: string
        state:
          maxLength: 100
          type: string
        vatNumber:
          maxLength: 50
          type: string
      type: object
info:
  title: Biller API Documentation
  version: 1.0.0
paths:
  /billers/all:
    get:
      responses:
        '200':
          description: A list of billers
      summary: Retrieve all billers
  /billers/create:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBiller'
        required: true
      responses:
        '200':
          description: Successfully created a new biller
      summary: Create a new biller
  /billers/update/{id}:
    delete:
      parameters:
        - description: ID of the biller to delete
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the biller
      summary: Delete a biller by ID
    put:
      parameters:
        - description: ID of the biller to update
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBiller'
        required: true
      responses:
        '200':
          description: Successfully updated the biller
      summary: Update an existing biller by ID
  /billers/{id}:
    get:
      parameters:
        - description: ID of the biller to retrieve
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Biller details
      summary: Retrieve a biller by ID
swagger: 3.1.0
